<?php

namespace AppBundle\Repository;

/**
 * VendorProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorProductRepository extends \Doctrine\ORM\EntityRepository
{
}
